projeto2/projeto2/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Modelo.Tabelas;
using Modelo.Cadastros;
using projeto2.Contexts;
using System.Data.Entity;
using System.Net;
using Servico.Cadastros;
using Servico.Tabelas;

namespace projeto2.Controllers
{
    public class ProdutosController : Controller
    {
        private ProdutoServico produtoServico = new ProdutoServico();
        private CategoriaServico categoriaServico = new CategoriaServico();
        private FabrivanteServico fabricanteServico = new FabrivanteServico();

        // GET: Produtos
        public ActionResult Index()
        {
            return View(produtoServico.ObterProdutosClassificadosPorNome());
        }

        private ActionResult ObterVisaoProdutoPorId(long? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produto produto = produtoServico.ObterProdutoPorId((long) id);
            if(produto == null)
            {
                return HttpNotFound();
            }
            return View(produto);

        }

        private void PopularViewBag(Produto produto = null)
        {
            if(produto == null)
            {
                ViewBag.CategoriaId = new SelectList(categoriaServico.ObtercategoriaClassificadasPorNome(), "CategoriaId", "Nome");
                ViewBag.FabricanteId = new SelectList(fabricanteServico.ObterFabricanteClassificadosPorNome(), "FabricanteId", "Nome");
            }
            else
            {
                ViewBag.CategoriaId = new SelectList(categoriaServico.ObtercategoriaClassificadasPorNome(), "CategoriaId", "Nome", produto.CategoriaId);
                ViewBag.FabricanteId = new SelectList(fabricanteServico.ObterFabricanteClassificadosPorNome(), "FabricanteId", "Nome", produto.FabricanteId);

            }
        }

        // GET: Produtos/Details/5
        public ActionResult Details(long? id)
        {
            PopularViewBag(produtoServico.ObterProdutoPorId((long) id));
            return ObterVisaoProdutoPorId(id);
        }

        // GET: Produtos/Create
        public ActionResult Create()
        {
            PopularViewBag();
            return View();
        }

        private ActionResult GravarProduto(Produto produto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    produtoServico.GravarProdutoi(produto);
                    return RedirectToAction("Index");
                }
                return View(produto);
            }
            catch
            {
                return View(produto);
            }
        }

        // POST: Produtos/Create
        [HttpPost]
        public ActionResult Create(Produto produto)
        {
            /*try
            {
                // TODO: Add insert logic here
                // context.Produtos.Add(produto);
                //context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(produto);
            }*/
            return GravarProduto(produto);
        }

        // GET: Produtos/Edit/5
        public ActionResult Edit(long? id)
        {
            /* if(id == null)
             {
                 return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
             }
             Produto produto = context.Produtos.Find(id);
             if(produto == null)
             {
                 return HttpNotFound();
             }
             ViewBag.CategoriaId = new SelectList(context.Categorias.OrderBy(b => b.Nome), "CategoriaId", "Nome", produto.CategoriaId);
             ViewBag.FabricanteId = new SelectList(context.Fabricantes.OrderBy(b => b.Nome), "FabricanteId", "Nome", produto.FabricanteId);
             return View(produto);*/
            PopularViewBag(produtoServico.ObterProdutoPorId((long)id));
            return ObterVisaoProdutoPorId(id);
        }

        // POST: Produtos/Edit/5
        [HttpPost]
        public ActionResult Edit(Produto produto)
        {
            /* try
             {
                 // TODO: Add update logic here
                 if (ModelState.IsValid)
                 {
                     context.Entry(produto).State = EntityState.Modified;
                     context.SaveChanges();
                     return RedirectToAction("Index");
                 }

                 return View(produto);
             }
             catch
             {
                 return View(produto);
             }*/
            return GravarProduto(produto);
        }

        // GET: Produtos/Delete/5
        public ActionResult Delete(long? id)
        {
            return ObterVisaoProdutoPorId(id);
        }

        // POST: Produtos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            /* try
             {
                 // TODO: Add delete logic here
                 Produto produto = context.Produtos.Find(id);
                 context.Produtos.Remove(produto);
                 context.SaveChanges();
                 TempData["Message"] = "Produto " + produto.Nome.ToUpper() + " for removido";
                 return RedirectToAction("Index");
             }
             catch
             {
                 return View();
             }*/
            try
            {
                Produto produto = produtoServico.EliminarProdutoId(id);
                TempData["Message"] = "Produto " + produto.Nome.ToUpper()
                + " foi removido";
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

projeto2/projeto2/Views/Produtos/Create.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Registrando um NOVO PRODUTO";}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Registro de um NOVO PRODUTO
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "",
                new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome,
                    htmlAttributes: new { @class =
                    "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class ="form-control" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.CategoriaId, "CategoriaId", htmlAttributes: new {@class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.FabricanteId, "FabricanteId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("FabricanteId",null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.FabricanteId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="panel-footer panel-info">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Adicionar Produto" class="btn btn-danger" />
                    @Html.ActionLink("Retornar para a listagem de PRODUTOS", "Index", null, new { @class = "btn btn-warning" })
                </div>
                <br />
                <br />
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('li').removeClass("active");
        $('#liProdutos').addClass("active");
    });
</script>

projeto2/projeto2/Views/Produtos/Delete.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Visualizando detalhes do PRODUTO a ser removido ";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Visualizando detalhes do PRODUTO a ser removido
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Nome,
                new { htmlAttributes = new { @class =
                "form-control", disabled = "disabled" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Categoria.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Categoria.Nome,
                new { htmlAttributes = new { @class =
                "form-control", disabled = "disabled" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Fabricante.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Fabricante.Nome,
                new { htmlAttributes = new { @class =
                "form-control", disabled = "disabled" } })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        <a href="#" class="btn btn-info" data-toggle="modal"
           data-target="#deleteConfirmationModal">Remover</a>
        @Html.ActionLink("Retornar para a listagem", "Index",
        null, new { @class = "btn btn-info" })
    </div>
</div>
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1"
     role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-ELTEismiss="modal" aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title">
                    Confirmação de exclusão de
                    PRODUTO
                </h4>
            </div>
            <div class="modal-body">
                <p>
                    Você está prestes a remover o produto @Model.
                    Nome.ToUpper() do cadastro.
                </p>
                <p>
                    <strong>
                        Você está certo que deseja prosseguir?
                    </strong>
                </p>
                @using (Html.BeginForm("Delete", "Produtos",
                FormMethod.Post, new
                {
                    @id = "delete-form",
                    role = "form"
                }))
                {
                    @Html.HiddenFor(m => m.ProdutoId)
                    @Html.AntiForgeryToken()
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        onclick="$('#delete-form').submit();">
                    Sim, exclua este produto.
                </button>
                <button type="button" class="btn btn-primary"
                        data-dismiss="modal">
                    Não, não exclua este produto.
                </button>
            </div>
        </div>
    </div>
</div>

    <script type="text/javascript">
        $(document).ready(function () {
        $('li').removeClass("active");
        $('#liProdutos').addClass("active");
        });
    </script>

projeto2/projeto2/Views/Produtos/Details.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Alterando os dados de um FABRICANTE";
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Visualizando detalhes de um FABRICANTE
    </div>
    <div class="panel-body">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Nome,
                new { htmlAttributes = new { @class =
                "form-control", disabled = "disabled" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Categoria.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Categoria.Nome,
                new { htmlAttributes = new { @class =
                "form-control", disabled = "disabled" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Fabricante.Nome)<br />
            <div class="input-group">
                <span class="input-group-addon">
                    <i class="glyphicon glyphicon-user"></i>
                </span>
                @Html.EditorFor(model => model.Fabricante.Nome,
                new { htmlAttributes = new { @class =
                "form-control", disabled = "disabled" } })
            </div>
        </div>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Alterar", "Edit", new { id = Model.
        ProdutoId }, new { @class = "btn btn-info" })
        @Html.ActionLink("Retornar para a listagem", "Index",
        null, new { @class = "btn btn-info" })
    </div>
</div>

    <script type="text/javascript">
$(document).ready(function () {
$('li').removeClass("active");
$('#liProdutos').addClass("active");
});
    </script>

projeto2/projeto2/Views/Produtos/Edit.cshtml
@model Modelo.Cadastros.Produto

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Visualizando os dados de um PRODUTO";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Alteração dos dados de um PRODUTO
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                <h4>Produto</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ProdutoId)
                <div class="form-group">
                    @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.CategoriaId, "CategoriaId", htmlAttributes: new {@class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CategoriaId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.FabricanteId, "FabricanteId", htmlAttributes: new {@class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("FabricanteId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.FabricanteId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Gravar alterações" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        $('li').removeClass("active");
        $('#liProdutos').addClass("active");
    });
</script>

projeto2/projeto2/Views/Produtos/Index.cshtml
@model IEnumerable<Modelo.Cadastros.Produto>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Listagem de PRODUTOS";
}
@if (@TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}
<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de PRODUTOS registrados
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model =>
                        model.ProdutoId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>Categoria</th>
                    <th>Fabricante</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ProdutoId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Categoria.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fabricante.Nome)
                        </td>
                        <td>
                            @Html.ActionLink("Alterar", "Edit", new { id = item. ProdutoId }) |
                            @Html.ActionLink("Detalhes", "Details", new { id = item.ProdutoId }) |
                            @Html.ActionLink("Eliminar", "Delete", new { id = item.ProdutoId })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
        @Html.ActionLink("Registrar um novo PRODUTO", "Create", null, new { @class = "btn btn-success" })
    </div>
</div>

<link href="@Url.Content("~/content/DataTables/css/dataTables.bootstrap.css")" rel="stylesheet">
<script src=" @Url.Content("~/scripts/DataTables/jquery. dataTables.js")" ></script>
<script src="@Url.Content("~/scripts/DataTables/dataTables.bootstrap.js")"></script>
    <script type="text/javascript">
        $(document).ready(function () {
        $('li').removeClass("active");
        $('#liProdutos').addClass("active");
        $('.table').dataTable({
        "order": [[1, "asc"]]
        });
        });
    </script>

projeto2/projeto2/Views/Produtos/_PorFabricante.cshtml
@model IEnumerable<Modelo.Cadastros.Produto>
<div class="panel panel-primary">
    <div class="panel-heading">
        Relação de PRODUTOS registrados para o fabricante
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.
                        ProdutoId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Nome)
                    </th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.
                            ProdutoId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.
                            Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.
                            Categoria.Nome)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="panel-footer panel-info">
    </div>
</div>